# version: '3.8'
# services:
#   db:
#     image: postgres
#     volumes:
#       - ./data/db:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=company
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=test
#   web:
#     build: .
#     command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
#     container_name: restapi
#     volumes:
#       - .:/RestApi
#     ports:
#       - "8000:8000"
    # depends_on:
    #   - db

# The docker-compose.yml file describes the services that make your app. In this example those services are a web server and database.

version: "3.8"
   
services:
     web:
        build: .
        container_name: RestApi
        # command: python manage.py runserver 0.0.0.0:8000
        command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
        depends_on:
            - pgdb
     pgdb:
        image: postgres
        container_name: postgres
        environment:
        - POSTGRES_DB=company
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=test