# Generated by Django 3.2 on 2021-05-21 14:43

import RestApi.storage_backends
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('c_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='C_ID')),
                ('c_name', models.CharField(max_length=50)),
                ('c_address', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('e_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='e_ID')),
                ('e_name', models.CharField(max_length=50)),
                ('e_phone', models.BigIntegerField()),
                ('e_address', models.CharField(max_length=1000)),
                ('e_pic', models.ImageField(storage=RestApi.storage_backends.StaticStorage(), upload_to='')),
                ('e_email', models.EmailField(max_length=254)),
                ('c_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='empManagement.company')),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
