# Generated by Django 3.2 on 2021-05-21 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Company'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': 'Employee'},
        ),
    ]
