# Generated by Django 3.2 on 2021-05-21 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empManagement', '0002_auto_20210521_2025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee'},
        ),
    ]
