# Generated by Django 3.2 on 2021-05-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empManagement', '0003_auto_20210521_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
